services:
    TheoBlin\UiBundle\Service\BoutonService:
      public: true
      autowire: true
      autoconfigure: true
    TheoBlin\UiBundle\Twig\ButtonExtension:
        arguments:
            $twig: '@twig'  # Injecte le service Twig
        tags: ['twig.extension']